version: "3.3"
services:
        dbos1:
                image: mysql:5.7
                volumes:
                        - mysql_storage_new:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_USER: docker
                        MYSQL_PASSWORD: redhat
                        MYSQL_DATABASE: mydatabase
        wordpressos:
                image: wordpress:5.1.1-php7.3-apache
                restart: always
                depends_on:
                        - dbos1
                ports:
                        - 8081:80
                environment:
                        WORDPRESS_DB_HOST: dbos1
                        WORDPRESS_DB_USER: docker
                        WORDPRESS_DB_PASSWORD: redhat
                        WORDPRESS_DB_NAME: mydatabase
                volumes:
                        - wp_storage_new:/var/www/html
volumes:
        wp_storage_new:
        mysql_storage_new: